---

version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: 'make start'
    ports:
      - 5555:5555
    volumes:
      - .:/usr/app
      - /tmp:/tmp
      - bundle_cache:/bundle_cache
    env_file: .env
    environment:
      REDIS_URL: redis://redis
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache
      GEM_PATH: /bundle_cache
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:16.3-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  nginx:
    image: nginx:1.25-alpine
    ports:
      - 8080:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  pgdata:
  bundle_cache:
  redis:
