---

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - fail2ban
    - git
    - imagemagick
    - python3-pip
    - python3-setuptools
    - software-properties-common
    - tzdata
    - ufw
    - virtualenv
    - "{{ required_packages }}"
