default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  username: <%= ENV['POSTGRES_USER'] %>

development:
  <<: *default
  database: hello_aws_development

test:
  <<: *default
  database: hello_aws_test

staging:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL', 'localhost') %>

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL', 'localhost') %>
