default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  username: <%= ENV['POSTGRES_USER'] %>

development:
  <<: *default
  database: hello_aws_development

test:
  <<: *default
  database: hello_aws_test

production:
  adapter: sqlite3
  timeout: 5000
  database: db/production.sqlite3
